# -*- coding: utf-8 -*-
"""Tugas 2 Comvis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j91Jc6IcBWjfhQqfeVAXczOXgbIwd41j
"""

import matplotlib.pyplot as plt
import numpy as np

from skimage.io import imread, imshow
from skimage.color import rgb2hsv, rgb2gray
from skimage.exposure import histogram, cumulative_distribution
from skimage.filters import threshold_otsu

from skimage.filters import gaussian

"""## Image Preprocessing"""

gambar= imread('Comvis_Image1.png')
imshow(gambar)

# smoothed_image = gaussian(gambar, sigma=1)
# imshow(smoothed_image)

"""## Grayscaling and Tresholding"""

gambar_gray = rgb2gray(gambar)
imshow(gambar_gray)

th = 0.64
gambar_gray_bw = gambar_gray < th
imshow(gambar_gray_bw)

rgb_gambar = np.zeros_like(gambar)
rgb_gambar[gambar_gray_bw] = gambar[gambar_gray_bw]
imshow(rgb_gambar)

"""## HSV Image"""

gambar_hsv = rgb2hsv(gambar)

fig, ax = plt.subplots(1, 3, figsize=(12,4))
ax[0].imshow(gambar_hsv[:,:,0], cmap='gray')
ax[0].set_title('Hue')
ax[1].imshow(gambar_hsv[:,:,1], cmap='gray')
ax[1].set_title('Saturation')
ax[2].imshow(gambar_hsv[:,:,2], cmap='gray')
ax[2].set_title('Value');

plt.imshow(gambar_hsv[:,:,0],cmap='hsv')
plt.colorbar()

"""## HSV Tresholding"""

#RED
lower_mask_1 = gambar_hsv[:,:,0] > 0.8
upper_mask_1 = gambar_hsv[:,:,0] < 1

lower_mask_2 = gambar_hsv[:,:,0] > 0
upper_mask_2 = gambar_hsv[:,:,0] < 0.1

mask = upper_mask_1*lower_mask_1 + upper_mask_2*lower_mask_2
plt.imshow(mask)
red = gambar[:,:,0]*mask
green = gambar[:,:,1]*mask
blue = gambar[:,:,2]*mask
gambar_masked = np.dstack((red,green,blue))
imshow(gambar_masked)

#GREEN
lower_mask = gambar_hsv[:,:,0] > 0.2
upper_mask = gambar_hsv[:,:,0] < 0.4
mask = upper_mask*lower_mask
plt.imshow(mask)

red = gambar[:,:,0]*mask
green = gambar[:,:,1]*mask
blue = gambar[:,:,2]*mask
gambar_masked = np.dstack((red,green,blue))
imshow(gambar_masked)

#BLUE
lower_mask = gambar_hsv[:,:,0] > 0.585
upper_mask = gambar_hsv[:,:,0] < 0.7
mask = upper_mask*lower_mask
plt.imshow(mask)

red = gambar[:,:,0]*mask
green = gambar[:,:,1]*mask
blue = gambar[:,:,2]*mask
gambar_masked = np.dstack((red,green,blue))
imshow(gambar_masked)

lower_mask_1 = gambar_hsv[:,:,0] > 0.8
upper_mask_1 = gambar_hsv[:,:,0] < 1

lower_mask_2 = gambar_hsv[:,:,0] > 0
upper_mask_2 = gambar_hsv[:,:,0] < 0.1

lower_mask_3 = gambar_hsv[:,:,0] > 0.585
upper_mask_3 = gambar_hsv[:,:,0] < 0.7

mask1 = upper_mask_1*lower_mask_1
mask2 = upper_mask_2*lower_mask_2
mask3 = upper_mask_3*lower_mask_3
mask = mask1 + mask2 + mask3

plt.imshow(mask)
red = gambar[:,:,0]*mask
green = gambar[:,:,1]*mask
blue = gambar[:,:,2]*mask
gambar_masked = np.dstack((red,green,blue))
imshow(gambar_masked)

plt.imshow(gambar_hsv[:,:,0],cmap='hsv')
plt.colorbar()

#GREEN
lower_mask = gambar_hsv[:,:,0] > 0.64
upper_mask = gambar_hsv[:,:,0] < 1
mask = upper_mask*lower_mask
plt.imshow(mask)

red = gambar[:,:,0]*mask
green = gambar[:,:,1]*mask
blue = gambar[:,:,2]*mask
gambar_masked = np.dstack((red,green,blue))
imshow(gambar_masked)

lower_mask_1 = gambar_hsv[:,:,0] > 0.5
upper_mask_1 = gambar_hsv[:,:,0] < 0.12

lower_mask_2 = gambar_hsv[:,:,0] > 0
upper_mask_2 = gambar_hsv[:,:,0] < 0.12

lower_mask_3 = gambar_hsv[:,:,0] > 0.5
upper_mask_3 = gambar_hsv[:,:,0] < 1

mask1 = upper_mask_1*lower_mask_1
mask2 = upper_mask_2*lower_mask_2
mask3 = upper_mask_3*lower_mask_3
mask = mask1 + mask2 + mask3

plt.imshow(mask)
red = gambar[:,:,0]*mask
green = gambar[:,:,1]*mask
blue = gambar[:,:,2]*mask
gambar_masked = np.dstack((red,green,blue))
imshow(gambar_masked)