# -*- coding: utf-8 -*-
"""Pengenalan_Pola1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XS0GgeduNB0XdGAJXARNa5gryBNi9FNj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

"""# Preprocessing Data"""

data = pd.read_csv("Magnitude_Objek_Langit.csv")

# Create NumPy arrays for each object type
star_magnitude = np.array(data[data["Object"] == "Star"]["Magnitude"])
dwarf_star_magnitude = np.array(data[data["Object"] == "Dwarf Star"]["Magnitude"])
galaxy_magnitude = np.array(data[data["Object"] == "Galaxy"]["Magnitude"])

# Print sample outputs
print("Star Magnitudes:", star_magnitude[:])  # Print first 10 values
print("Dwarf Star Magnitudes:", dwarf_star_magnitude[:])
print("Galaxy Magnitudes:", galaxy_magnitude[:])

"""# Visualisasi Data"""

plt.hist(star_magnitude, color='blue', bins=20, alpha=0.7, label='Star')
plt.hist(dwarf_star_magnitude, color='orange', bins=20, alpha=0.7, label='Dwarf Star')
plt.hist(galaxy_magnitude, color='green', bins=20, alpha=0.7, label='Galaxy')

plt.xlabel('Magnitude')
plt.ylabel('Frekuensi')
plt.title('Histogram Magnitude Objek Langit')
plt.legend()
plt.show()

"""# Distribusi Data"""

# Star Plot
star_mean = np.mean(star_magnitude)
star_std = np.std(star_magnitude)
x_star = np.linspace(min(star_magnitude), max(star_magnitude), 1000)
pdf_star = stats.norm.pdf(x_star, star_mean, star_std)
plt.plot(x_star, pdf_star, color='blue', label='Star Magnitude')
plt.fill_between(x_star, pdf_star, color='blue', alpha=0.3)


# Dwarf Star
dwarf_mean = np.mean(dwarf_star_magnitude)
dwarf_std = np.std(dwarf_star_magnitude)
x_dwarf = np.linspace(min(dwarf_star_magnitude), max(dwarf_star_magnitude), 1000)
pdf_dwarf = stats.norm.pdf(x_dwarf, dwarf_mean, dwarf_std)
plt.plot(x_dwarf, pdf_dwarf, color='orange', label='Dwarf Star Magnitude')
plt.fill_between(x_dwarf, pdf_dwarf, color='orange', alpha=0.3)

# Galaxy
galaxy_mean = np.mean(galaxy_magnitude)
galaxy_std = np.std(galaxy_magnitude)
x_galaxy = np.linspace(min(galaxy_magnitude), max(galaxy_magnitude), 1000)
pdf_galaxy = stats.norm.pdf(x_galaxy, galaxy_mean, galaxy_std)
plt.plot(x_galaxy, pdf_galaxy, color='green', label='Galaxy Magnitude')
plt.fill_between(x_galaxy, pdf_galaxy, color='green', alpha=0.3)

plt.xlabel('Magnitude')
plt.ylabel('Probability Density')
plt.title('Distribusi Magnitude Gaussian')
plt.ylim((0.04, 0.180))
plt.legend()
plt.show()

def Gaussian_Bell (x, std, mean):
  temp = 1/(std*(2*np.pi)**0.5)
  temp = temp * np.exp(-0.5*((x-mean)/std)**2)
  return temp

"""#"""

X = float(input("Magnitude: "))

A = Gaussian_Bell(X, star_std, star_mean)
B = Gaussian_Bell(X, dwarf_std, dwarf_mean)
C = Gaussian_Bell(X, galaxy_std, galaxy_mean)

object_types = ["Star", "Dwarf Star", "Galaxy"]
object_mean = [star_mean, dwarf_mean, galaxy_mean]
Comparison = np.array([A, B, C])
max_index = np.argmax(Comparison)
Error_Rate = round(np.abs((X - object_mean[max_index])*100/(X + object_mean[max_index])), 2)
print("Highest Probability:", Comparison[max_index]*100, "%")
print("Object Type:", object_types[max_index])
print("Error Rate:", Error_Rate, "%")